#spring:
#  cloud:
#    gateway:
#      routes:
##        - id: after_route
##          uri: https://www.baidu.com/
##          predicates:
##            - After=2020-06-29T06:06:06+08:00[Asia/Shanghai]
#        - id: before_route
#          uri: https://www.ailijie.top
#          predicates:
#            - After=2020-06-20T06:06:06+08:00[Asia/Shanghai]
#        - id: myRoute
#          uri: lb://feign-service
#          predicates:
#            - Path=/feign-service/**
#            ## 熔断
#          - name: Hystrix
#            args:
#              name: fallbackcmd
#              ### fallback 时调用的方法 http://localhost:8000/fallback
#              fallbackUri: forward:/fallback

#跨域
#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#                POST
#                DELETE
#                PUT
#                OPTION